version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::586770803976:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-Q3AZ7QF05I25"

[test]
[test.pipeline_bootstrap]
[test.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::357993141891:role/aws-sam-cli-managed-test-pip-PipelineExecutionRole-NKPM1BUMN4W"
cloudformation_execution_role = "arn:aws:iam::357993141891:role/aws-sam-cli-managed-test-CloudFormationExecutionR-JFYA4IL7PVX7"
artifacts_bucket = "aws-sam-cli-managed-test-pipeline-artifactsbucket-z6vh54gbtxuk"
image_repository = ""
region = "us-east-1"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::586770803976:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-D5ILXK3H9N85"
cloudformation_execution_role = "arn:aws:iam::586770803976:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-56WRG3TRASVG"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-11rchxaekeooc"
image_repository = ""
region = "us-east-1"
